# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
    
form_loisir:
    path: /loisir/create
    controller: App\controller
    
form_formation:
    path: /formation/create
    controller: App\controller\LuckyController::formation
    
form_experience:
    path: /experience/create
    controller: App\controller\LuckyController::experience
    
form_loisir:
    path: /loisir/create
    controller: App\controller\LuckyController::loisir